src/main/resources/static/css/board.css
src/main/resources/static/css/boardWrite.css
src/main/resources/static/js/board.js
src/main/resources/static/js/boardWrite.js
src/main/resources/templates/board/board.html
src/main/resources/templates/board/boardWrite.html

수정 사항 업데이트

---

src/main/java/com/example/kovengerss/domain/vo/AdminVO.java
src/main/java/com/example/kovengerss/domain/vo/AnswerVO.java
src/main/java/com/example/kovengerss/domain/vo/BoardVO.java
src/main/java/com/example/kovengerss/domain/vo/IdealVO.java
src/main/java/com/example/kovengerss/domain/vo/LikeVO.java
src/main/java/com/example/kovengerss/domain/vo/MessageVO.java
src/main/java/com/example/kovengerss/domain/vo/PointVO.java
src/main/java/com/example/kovengerss/domain/vo/ReplyVO.java
src/main/java/com/example/kovengerss/domain/vo/UserVO.java
src/main/java/com/example/kovengerss/mapper/BoardMapper.java
src/main/java/com/example/kovengerss/myBatis/MyBatisConfig.java
src/main/resources/config/config.xml

boardmapper 내용

---

src/main/java/com/example/kovengerss/mapper/UserMapper.java

UserMapper

---

src/main/java/com/example/kovengerss/domain/dao/BoardDAO.java
src/main/java/com/example/kovengerss/domain/dao/UserDAO.java
src/main/java/com/example/kovengerss/domain/service/BoardService.java
src/main/java/com/example/kovengerss/domain/service/BoardServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/UserService.java
src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java

BoardDAO, UserDAO / BoardService, UserService

BoardDAO, UserDAO / BoardService, UserService

---

src/main/java/com/example/kovengerss/domain/controller/BoardController.java
src/main/java/com/example/kovengerss/domain/dao/AdminDAO.java
src/main/java/com/example/kovengerss/domain/dao/AnswerDAO.java
src/main/java/com/example/kovengerss/domain/dao/IdealDAO.java
src/main/java/com/example/kovengerss/domain/dao/LikeDAO.java
src/main/java/com/example/kovengerss/domain/dao/MessageDAO.java
src/main/java/com/example/kovengerss/domain/dao/PointDAO.java
src/main/java/com/example/kovengerss/domain/dao/ReplyDAO.java
src/main/java/com/example/kovengerss/domain/service/AdminService.java
src/main/java/com/example/kovengerss/domain/service/AdminServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/AnswerService.java
src/main/java/com/example/kovengerss/domain/service/AnswerServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/BoardServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/IdealService.java
src/main/java/com/example/kovengerss/domain/service/IdealServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/LikeService.java
src/main/java/com/example/kovengerss/domain/service/LikeServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/MessageService.java
src/main/java/com/example/kovengerss/domain/service/MessageServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/PointService.java
src/main/java/com/example/kovengerss/domain/service/PointServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/ReplyService.java
src/main/java/com/example/kovengerss/domain/service/ReplyServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java

DAO, Service, Controller 1차 수정

DAO, Service, Controller 1차 수정

---

src/main/resources/static/css/appilBoard.css
src/main/resources/static/css/board.css
src/main/resources/static/css/boardWrite.css
src/main/resources/static/js/appilBoard.js
src/main/resources/static/js/board.js
src/main/resources/static/js/reviewBoard.js
src/main/resources/templates/board/appilBoardList.html
src/main/resources/templates/board/boardWrite.html
src/main/resources/templates/board/boardlist.html
src/main/resources/templates/board/reviewBoardList.html

게시판 ,css, js 추가 수정 했습니다

---

src/main/java/com/example/kovengerss/domain/controller/BoardController.java
src/main/java/com/example/kovengerss/domain/dao/BoardDAO.java
src/main/java/com/example/kovengerss/domain/service/BoardService.java

Service 3차 수정

---

src/main/java/com/example/kovengerss/domain/dao/AnswerDAO.java
src/main/java/com/example/kovengerss/domain/dao/BoardDAO.java
src/main/java/com/example/kovengerss/domain/dao/LikeDAO.java
src/main/java/com/example/kovengerss/domain/dao/MessageDAO.java
src/main/java/com/example/kovengerss/domain/dao/ReplyDAO.java
src/main/java/com/example/kovengerss/domain/service/AnswerService.java
src/main/java/com/example/kovengerss/domain/service/AnswerServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/BoardService.java
src/main/java/com/example/kovengerss/domain/service/BoardServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/LikeService.java
src/main/java/com/example/kovengerss/domain/service/LikeServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/MessageService.java
src/main/java/com/example/kovengerss/domain/service/MessageServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/ReplyService.java
src/main/java/com/example/kovengerss/domain/service/ReplyServiceImpl.java

Service 4차 수정

---

src/main/java/com/example/kovengerss/domain/controller/AdminController.java
src/main/java/com/example/kovengerss/domain/controller/BoardController.java
src/main/java/com/example/kovengerss/domain/controller/MessageController.java
src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/dao/AnswerDAO.java
src/main/java/com/example/kovengerss/domain/dao/BoardDAO.java
src/main/java/com/example/kovengerss/domain/dao/LikeDAO.java
src/main/java/com/example/kovengerss/domain/dao/MessageDAO.java
src/main/java/com/example/kovengerss/domain/dao/ReplyDAO.java
src/main/java/com/example/kovengerss/domain/dao/UserDAO.java
src/main/resources/templates/board/boardWrite.html

Controller 수정 1차

---

src/main/resources/templates/adminpage.html

어드민 페이지 픽스

---

src/main/java/com/example/kovengerss/domain/controller/BoardController.java
src/main/java/com/example/kovengerss/domain/controller/MessageController.java
src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/dao/AdminDAO.java
src/main/java/com/example/kovengerss/domain/dao/BoardDAO.java
src/main/java/com/example/kovengerss/domain/dao/CoupleIdealDAO.java
src/main/java/com/example/kovengerss/domain/dao/IdealDAO.java
src/main/java/com/example/kovengerss/domain/dao/LikeDAO.java
src/main/java/com/example/kovengerss/domain/dao/MessageDAO.java
src/main/java/com/example/kovengerss/domain/dao/PointDAO.java
src/main/java/com/example/kovengerss/domain/dao/UserDAO.java
src/main/java/com/example/kovengerss/domain/service/AdminService.java
src/main/java/com/example/kovengerss/domain/service/AdminServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/BoardService.java
src/main/java/com/example/kovengerss/domain/service/BoardServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/CoupleIdealService.java
src/main/java/com/example/kovengerss/domain/service/CoupleIdealServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/IdealService.java
src/main/java/com/example/kovengerss/domain/service/IdealServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/LikeService.java
src/main/java/com/example/kovengerss/domain/service/LikeServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/PointService.java
src/main/java/com/example/kovengerss/domain/service/PointServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/UserService.java
src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java

Controller 2차 작업

---

src/main/java/com/example/kovengerss/domain/controller/BoardController.java
src/main/java/com/example/kovengerss/domain/controller/MessageController.java
src/main/java/com/example/kovengerss/domain/controller/PointController.java
src/main/java/com/example/kovengerss/domain/controller/UserController.java

Controller 주석 작업

---

src/main/resources/static/css/choice.css
src/main/resources/static/css/find.css
src/main/resources/static/css/login.css
src/main/resources/static/css/love.css
src/main/resources/static/css/marry.css
src/main/resources/static/css/sign.css
src/main/resources/templates/choice.html
src/main/resources/templates/find.html
src/main/resources/templates/letter.html
src/main/resources/templates/login.html
src/main/resources/templates/love.html
src/main/resources/templates/marry.html
src/main/resources/templates/sign.html

header,footer적용

---

src/main/java/com/example/kovengerss/domain/vo/BlackListVO.java
src/main/java/com/example/kovengerss/mapper/BlackListMapper.java
src/main/resources/config/config.xml
src/main/resources/mapper/BlackListMapper.xml
src/main/resources/mapper/BoardMapper.xml
src/test/java/com/example/kovengerss/Mapper/BoardMapperTests.java

블랙리스트 vo mapper xml 추가

---

src/main/java/com/example/kovengerss/domain/controller/AdminController.java
src/main/java/com/example/kovengerss/domain/controller/BlackListController.java
src/main/java/com/example/kovengerss/domain/controller/MessageController.java
src/main/java/com/example/kovengerss/domain/dao/BlackListDAO.java
src/main/java/com/example/kovengerss/domain/service/BlackListService.java
src/main/java/com/example/kovengerss/domain/service/BlackListServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/CoupleIdealServiceImpl.java

컨트롤 설계 최종(확인 전)

---

src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/dao/UserDAO.java
src/main/java/com/example/kovengerss/domain/service/UserService.java
src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java
src/main/java/com/example/kovengerss/mapper/UserMapper.java
src/main/resources/mapper/UserMapper.xml
src/test/java/com/example/kovengerss/Mapper/UserMapperTests.java

종임님 충돌 해결 1차

---

src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/resources/templates/find.html

유저 컨트롤러 수정

---

pom.xml
src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/dao/UserDAO.java
src/main/java/com/example/kovengerss/domain/service/SmsService.java
src/main/java/com/example/kovengerss/domain/service/SmsServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/UserService.java
src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java
src/main/java/com/example/kovengerss/mapper/UserMapper.java
src/main/resources/mapper/UserMapper.xml
src/main/resources/templates/find.html
src/main/resources/templates/myPage.html

login Session 받아오기, smsService 1차적 구현

login Session 받아오기, smsService 1차적 구현

---

src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/dao/UserDAO.java
src/main/java/com/example/kovengerss/domain/service/SmsServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/UserService.java
src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java
src/main/java/com/example/kovengerss/mapper/UserMapper.java
src/main/resources/mapper/UserMapper.xml
src/main/resources/static/js/find.js
src/main/resources/templates/find.html

아이디 찾기 구현(SMS인증)

---

src/main/java/com/example/kovengerss/domain/controller/IdealContoller.java
src/main/java/com/example/kovengerss/domain/controller/MessageController.java
src/main/java/com/example/kovengerss/domain/vo/IdealVO.java
src/main/java/com/example/kovengerss/mapper/IdealMapper.java
src/main/resources/mapper/IdealMapper.xml
src/main/resources/mapper/MessageMapper.xml
src/main/resources/templates/letter.html
src/main/resources/templates/marry.html
src/main/resources/templates/myPage.html
src/test/java/com/example/kovengerss/Mapper/IdealMapperTests.java

idealController 기능구현

---

src/main/java/com/example/kovengerss/domain/controller/BoardController.java
src/main/java/com/example/kovengerss/domain/dao/BoardDAO.java
src/main/java/com/example/kovengerss/domain/service/BoardService.java
src/main/java/com/example/kovengerss/domain/service/BoardServiceImpl.java
src/main/java/com/example/kovengerss/mapper/BoardMapper.java
src/main/resources/mapper/BoardMapper.xml
src/main/resources/templates/board/board.html
src/main/resources/templates/board/boardUpdate.html
src/test/java/com/example/kovengerss/Mapper/BoardMapperTests.java

게시판 작성, 수정 완료

---

pom.xml
src/main/java/com/example/kovengerss/domain/controller/MainController.java
src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/dao/UserDAO.java
src/main/java/com/example/kovengerss/domain/service/UserService.java
src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java
src/main/java/com/example/kovengerss/mapper/UserMapper.java
src/main/resources/mapper/UserMapper.xml
src/main/resources/templates/find.html
src/main/resources/templates/main.html

아이디 찾기, 비밀번호 찾기, 회원탈퇴 성공

---

src/main/java/com/example/kovengerss/domain/controller/MainController.java
src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java
src/main/resources/mapper/UserMapper.xml
src/main/resources/static/css/main.css
src/main/resources/templates/main.html

메인페이지 게시글 1차 작업 중 입니다.

---

src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java
src/main/resources/templates/main.html
src/main/resources/templates/myPage.html
src/main/resources/templates/myPagePoint.html

아이디 찾기, 비밀번호 찾기, 회원탈퇴 및 김건우님 html

아이디 찾기, 비밀번호 찾기, 회원탈퇴 및 김건우님 html

---

src/main/java/com/example/kovengerss/domain/controller/AppilBoardController.java
src/main/java/com/example/kovengerss/domain/controller/BoardController.java
src/main/java/com/example/kovengerss/domain/controller/ReplyController.java
src/main/java/com/example/kovengerss/domain/dao/ReplyDAO.java
src/main/java/com/example/kovengerss/domain/service/BoardServiceAppil.java
src/main/java/com/example/kovengerss/domain/service/ReplyService.java
src/main/java/com/example/kovengerss/domain/service/ReplyServiceImpl.java
src/main/java/com/example/kovengerss/mapper/ReplyMapper.java
src/main/resources/mapper/LikeMapper.xml
src/main/resources/mapper/ReplyMapper.xml
src/main/resources/static/js/board.js
src/main/resources/static/js/moment.js
src/main/resources/static/js/reply.js
src/main/resources/templates/board/appilBoard.html
src/main/resources/templates/board/appilBoardUpdate.html
src/main/resources/templates/board/board.html
src/main/resources/templates/board/boardUpdate.html
src/main/resources/templates/error.html
src/test/java/com/example/kovengerss/Mapper/BoardMapperTests.java
src/test/java/com/example/kovengerss/Mapper/ReplyMapperTests.java
src/test/java/com/example/kovengerss/controller/BoardControllerTests.java
src/test/java/com/example/kovengerss/domain/dao/ReplyDAOTests.java
src/test/java/com/example/kovengerss/domain/service/ReplyServiceTests.java

어필 게시판 수정 완료 댓글 구현 전

---

src/main/java/com/example/kovengerss/domain/controller/AdminController.java
src/main/java/com/example/kovengerss/domain/dao/AdminDAO.java
src/main/java/com/example/kovengerss/domain/service/AdminService.java
src/main/java/com/example/kovengerss/domain/service/AdminServiceImpl.java
src/main/java/com/example/kovengerss/domain/vo/Criteria1.java
src/main/java/com/example/kovengerss/domain/vo/Criteria2.java
src/main/java/com/example/kovengerss/domain/vo/Criteria3.java
src/main/java/com/example/kovengerss/domain/vo/Page1DTO.java
src/main/java/com/example/kovengerss/domain/vo/Page2DTO.java
src/main/java/com/example/kovengerss/domain/vo/Page3DTO.java
src/main/java/com/example/kovengerss/mapper/AdminMapper.java
src/main/resources/mapper/AdminMapper.xml
src/main/resources/static/css/adminpage.css
src/main/resources/templates/adminAppilField.html
src/main/resources/templates/adminBlackList.html
src/main/resources/templates/adminBoardField.html
src/main/resources/templates/adminPointField.html
src/main/resources/templates/adminReviewField.html
src/test/java/com/example/kovengerss/Mapper/AdminMapperTests.java

관리자 페이지 페이징 수정중

---

src/main/java/com/example/kovengerss/domain/controller/MessageController.java
src/main/resources/templates/pick.html

message ideal

---

src/main/java/com/example/kovengerss/domain/controller/IdealContoller.java
src/main/java/com/example/kovengerss/domain/controller/MessageController.java
src/main/java/com/example/kovengerss/domain/dao/MessageDAO.java
src/main/java/com/example/kovengerss/domain/service/MessageService.java
src/main/java/com/example/kovengerss/domain/service/MessageServiceImpl.java
src/main/java/com/example/kovengerss/mapper/MessageMapper.java
src/main/resources/mapper/MessageMapper.xml
src/main/resources/templates/letter.html
src/main/resources/templates/pick.html
src/test/java/com/example/kovengerss/Mapper/MessageMapperTests.java

message getlist수정

---

src/main/java/com/example/kovengerss/domain/dao/IdealDAO.java
src/main/java/com/example/kovengerss/domain/service/IdealService.java
src/main/java/com/example/kovengerss/domain/service/IdealServiceImpl.java
src/main/java/com/example/kovengerss/mapper/IdealMapper.java
src/main/resources/mapper/IdealMapper.xml
src/main/resources/static/css/pick.css
src/main/resources/templates/letter.html
src/main/resources/templates/marry.html
src/main/resources/templates/pick.html
src/main/resources/templates/updateMarry.html
src/test/java/com/example/kovengerss/Mapper/IdealMapperTests.java

marry.html 글자수제한 추가

---

src/main/java/com/example/kovengerss/domain/controller/AdminController.java
src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/dao/AdminDAO.java
src/main/java/com/example/kovengerss/domain/service/AdminService.java
src/main/java/com/example/kovengerss/domain/service/AdminServiceImpl.java
src/main/java/com/example/kovengerss/domain/vo/Criteria.java
src/main/java/com/example/kovengerss/mapper/AdminMapper.java
src/main/resources/mapper/AdminMapper.xml
src/main/resources/mapper/UserMapper.xml
src/main/resources/templates/adminAppilField.html
src/main/resources/templates/adminBlackList.html
src/main/resources/templates/adminBoardField.html
src/main/resources/templates/adminPointField.html
src/main/resources/templates/adminRead.html
src/main/resources/templates/adminReviewField.html
src/main/resources/templates/adminpage.html
src/test/java/com/example/kovengerss/Mapper/AdminMapperTests.java

어드민 삭제, 유저 멥퍼추가

---

src/main/java/com/example/kovengerss/domain/controller/MainController.java
src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/service/SmsServiceImpl.java
src/main/resources/templates/find.html
src/main/resources/templates/main.html
src/main/resources/templates/myPage.html

메인페이지 헤더 로그인 로그아웃 구분 설정 / 메인페이지 게시글 뿌려주기

메인페이지 헤더 로그인 로그아웃 구분 설정 / 메인페이지 게시글 뿌려주기

---

src/main/java/com/example/kovengerss/domain/vo/IdealVO.java
src/main/resources/templates/myPage.html

마이페이지 이름 추가

---

src/main/java/com/example/kovengerss/domain/controller/BoardController.java
src/main/resources/templates/board/appilBoard.html
src/main/resources/templates/board/board.html
src/main/resources/templates/board/boardWrite.html
src/main/resources/templates/board/reviewBoard.html
src/main/resources/templates/login.html

게시판 작성시 null 값일때 막는 것과 로그인 안되있으면 로그인페이지로 이동으로 수정

---

src/main/java/com/example/kovengerss/domain/controller/AdminController.java
src/main/java/com/example/kovengerss/domain/dao/AdminDAO.java
src/main/java/com/example/kovengerss/domain/service/AdminService.java
src/main/java/com/example/kovengerss/domain/service/AdminServiceImpl.java
src/main/java/com/example/kovengerss/mapper/AdminMapper.java
src/main/resources/mapper/AdminMapper.xml
src/main/resources/templates/adminPointField.html
src/test/java/com/example/kovengerss/Mapper/AdminMapperTests.java

관리자 포인트페이지 추가

---

src/main/java/com/example/kovengerss/domain/controller/AppilBoardController.java
src/main/java/com/example/kovengerss/domain/controller/BoardController.java
src/main/java/com/example/kovengerss/domain/controller/ReviewBoardController.java
src/main/java/com/example/kovengerss/domain/vo/LikeVO.java
src/main/java/com/example/kovengerss/mapper/LikeMapper.java
src/main/resources/mapper/LikeMapper.xml
src/main/resources/templates/board/appilBoardUpdate.html
src/main/resources/templates/board/boardUpdate.html
src/main/resources/templates/board/boardWrite.html
src/main/resources/templates/board/reviewBoardUpdate.html
src/test/java/com/example/kovengerss/Mapper/LikeMapperTests.java

2022 06 29 작업 pr

---

src/main/java/com/example/kovengerss/domain/controller/LikeController.java
src/main/java/com/example/kovengerss/domain/dao/LikeDAO.java
src/main/java/com/example/kovengerss/domain/service/LikeService.java
src/main/java/com/example/kovengerss/domain/service/LikeServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/ReplyService.java
src/main/java/com/example/kovengerss/mapper/LikeMapper.java
src/main/resources/static/js/like.js
src/main/resources/templates/board/board.html

하트 mapper/ dao / service 완성

---

src/main/java/com/example/kovengerss/domain/controller/AdminController.java
src/main/java/com/example/kovengerss/domain/vo/Criteria1.java
src/main/java/com/example/kovengerss/domain/vo/Criteria2.java
src/main/java/com/example/kovengerss/domain/vo/Criteria3.java
src/main/resources/static/css/adminRead.css
src/main/resources/static/js/sign.js
src/main/resources/templates/adminAppilField.html
src/main/resources/templates/adminBlackList.html
src/main/resources/templates/adminBoardField.html
src/main/resources/templates/adminPointField.html
src/main/resources/templates/adminRead.html
src/main/resources/templates/adminReviewField.html
src/main/resources/templates/login.html

어드민 페이지 상세글 수정, 회원가입 오류 수정

---

src/main/java/com/example/kovengerss/domain/controller/AdminController.java
src/main/java/com/example/kovengerss/domain/dao/AdminDAO.java
src/main/java/com/example/kovengerss/domain/service/AdminService.java
src/main/java/com/example/kovengerss/domain/service/AdminServiceImpl.java
src/main/java/com/example/kovengerss/mapper/AdminMapper.java
src/main/resources/mapper/AdminMapper.xml
src/main/resources/static/css/adminGetUser.css
src/main/resources/static/css/adminpage.css
src/main/resources/templates/adminAppilField.html
src/main/resources/templates/adminBlackList.html
src/main/resources/templates/adminBoardField.html
src/main/resources/templates/adminGetUser.html
src/main/resources/templates/adminIdealRead.html
src/main/resources/templates/adminPointField.html
src/main/resources/templates/adminRead.html
src/main/resources/templates/adminReviewField.html
src/main/resources/templates/adminpage.html

어드민 페이지 유저 정보추가

---

src/main/java/com/example/kovengerss/domain/controller/LikeController.java
src/main/java/com/example/kovengerss/domain/controller/ReplyListController.java
src/main/java/com/example/kovengerss/domain/controller/WarringController.java
src/main/java/com/example/kovengerss/domain/dao/LikeDAO.java
src/main/java/com/example/kovengerss/domain/dao/WarringDAO.java
src/main/java/com/example/kovengerss/domain/service/LikeService.java
src/main/java/com/example/kovengerss/domain/service/LikeServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/WarringService.java
src/main/java/com/example/kovengerss/domain/service/WarringServicelmpl.java
src/main/java/com/example/kovengerss/domain/vo/WarringVO.java
src/main/java/com/example/kovengerss/mapper/LikeMapper.java
src/main/java/com/example/kovengerss/mapper/WarringMapper.java
src/main/resources/config/config.xml
src/main/resources/mapper/LikeMapper.xml
src/main/resources/mapper/ReplyMapper.xml
src/main/resources/mapper/WarringMapper.xml
src/main/resources/static/js/board.js
src/main/resources/static/js/like.js
src/main/resources/static/js/warring.js
src/main/resources/templates/board/board.html
src/main/resources/templates/board/boardList.html
src/test/java/com/example/kovengerss/Mapper/LikeMapperTests.java
src/test/java/com/example/kovengerss/Mapper/WarringMapperTests.java
src/test/java/com/example/kovengerss/domain/dao/LikeDAOTests.java

하트 카운트담기, 신고 카운트 담기 완료

---

src/main/java/com/example/kovengerss/domain/service/WarringService.java
src/main/resources/static/js/like.js
src/main/resources/static/js/reply.js
src/main/resources/templates/board/appilBoard.html
src/main/resources/templates/board/appilBoardList.html
src/main/resources/templates/board/board.html
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/reviewBoard.html
src/main/resources/templates/board/reviewBoardList.html
src/main/resources/templates/selectHuman.html

댓글 날짜 초 분 시 로 나오게 + 이후에는 년월일

---

src/main/java/com/example/kovengerss/domain/controller/MessageController.java
src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/java/com/example/kovengerss/domain/dao/PointDAO.java
src/main/java/com/example/kovengerss/domain/dao/ReplyDAO.java
src/main/java/com/example/kovengerss/domain/dao/UserDAO.java
src/main/java/com/example/kovengerss/domain/service/BoardService.java
src/main/java/com/example/kovengerss/domain/service/MessageService.java
src/main/java/com/example/kovengerss/domain/service/MessageServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/PointService.java
src/main/java/com/example/kovengerss/domain/service/PointServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/ReplyService.java
src/main/java/com/example/kovengerss/mapper/BoardMapper.java
src/main/java/com/example/kovengerss/mapper/PointMapper.java
src/main/java/com/example/kovengerss/mapper/ReplyMapper.java
src/main/java/com/example/kovengerss/mapper/UserMapper.java
src/main/resources/mapper/PointMapper.xml
src/main/resources/mapper/ReplyMapper.xml
src/main/resources/mapper/UserMapper.xml
src/main/resources/templates/main.html
src/main/resources/templates/myPageAnswer.html
src/main/resources/templates/myPagePoint.html
src/main/resources/templates/myPageText.html

최종 마무리 단계 - 충전 내역 , 사용 내역-

---

src/main/java/com/example/kovengerss/domain/controller/AdminController.java
src/main/java/com/example/kovengerss/domain/dao/AdminDAO.java
src/main/java/com/example/kovengerss/domain/service/AdminService.java
src/main/java/com/example/kovengerss/domain/service/AdminServiceImpl.java
src/main/java/com/example/kovengerss/mapper/AdminMapper.java
src/main/resources/mapper/AdminMapper.xml
src/main/resources/templates/adminPointField.html
src/test/java/com/example/kovengerss/Mapper/AdminMapperTests.java

포인트 회수 기능 추가

---

src/main/resources/static/css/adminGetUser.css
src/main/resources/static/css/adminRead.css
src/main/resources/static/css/adminpage.css
src/main/resources/templates/adminBoardField.html
src/main/resources/templates/adminpage.html

어드민 페이지 검색 css수정

---

src/main/java/com/example/kovengerss/domain/controller/MainController.java
src/main/java/com/example/kovengerss/domain/dao/PointDAO.java
src/main/java/com/example/kovengerss/domain/service/PointService.java
src/main/java/com/example/kovengerss/domain/service/PointServiceImpl.java
src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java
src/main/resources/templates/company.html
src/main/resources/templates/myPagePoint.html

최종 마무리(주석 처리, 코드 가독성 및 간결화 작업)

최종 마무리(주석 처리, 코드 가독성 및 간결화 작업)

---

src/main/java/com/example/kovengerss/domain/controller/UserController.java
src/main/resources/templates/adminIdealRead.html
src/main/resources/templates/adminRead.html
src/main/resources/templates/login.html
src/main/resources/templates/myPage.html
src/main/resources/templates/myPagePoint.html
src/main/resources/templates/sign.html

마이페이지 회원탈퇴 추가,
로그인, 회원가입 헤더 css추가
글 내용 작성 시 박스 넘어가는 오류 수정 완료

회원탈퇴 수정, 오류 수정

---

src/main/resources/templates/myPageAnswer.html
src/main/resources/templates/myPageMatching.html
src/main/resources/templates/myPagePoint.html
src/main/resources/templates/myPageText.html

헤더 부분 최종 수정.

---

src/main/resources/static/js/sign.js

회원가입 알럿창 오류 수정

---

src/main/java/com/example/kovengerss/domain/service/UserServiceImpl.java

이메일 비밀번호 나와서 수정 후 PR
